// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uchmplwgzdviumuqioyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjaG1wbHdnemR2aXVtdXFpb3l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTA1OTcsImV4cCI6MjA2Mjg4NjU5N30.GEq18VWJ_PgSR22ZPL-lDFgPqy9409jSJymG-x7vIDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);